#!/usr/bin/env bash

battery_info="$(acpi | awk -F, '/^Battery 0:/ { gsub(/Battery 0: /,""); print $1 $2 $3 }')"

read -r state percentage remaining <<< "$battery_info"

declare output color

output="$percentage"

charging_color="#61C766" # green
discharging_color="#EC7875" # red

if [[ "$state" == "Discharging" ]]; then
  color="$discharging_color" # red
elif [[ "$state" == "Charging" ]]; then
  color="$charging_color" # green
elif [[ "$state" == "Fully-charged" ]]; then
  color="$charging_color"
  output="100%"
  echo "^c$charging_color^^d^$output"
  exit
fi

declare icon

percentage="${percentage::-1}"
if (( percentage && percentage < 20 )); then
  icon=""
elif (( percentage >= 20 && percentage < 40 )); then
  icon=""
elif (( percentage >= 40 && percentage < 60 )); then
  icon=""
elif (( percentage >= 60 && percentage < 80 )); then
  icon=""
elif (( percentage >= 80 && percentage <= 100 )); then
  icon=""
fi

echo "^c$color^$icon^d^$output^d^($remaining)"
