#!/usr/bin/env bash

set -e

declare -a layouts=(
  us
  ru
  de
)

declare curr_layout; curr_layout="$(klayout)"

declare next_layout

for i in "${!layouts[@]}"; do
  if [[ "$curr_layout" == "${layouts[i]}" ]]; then
    (( i + 1 >= ${#layouts[@]} )) && next_layout="${layouts[0]}" \
      || next_layout="${layouts[i+1]}"
  fi
done

setxkbmap "$next_layout"
kill -45 "$(pidof dwmblocks)" &> /dev/null
