#!/usr/bin/env python3

import json
import subprocess as sp

TERM_STAGE = "[terminted]"

def show_widget():
    plays = json.loads(sp.check_output(["c4", "ps", "-o", "json"]))
    visited = []
    play_num = 0

    for play in plays:
        play_id = play["c4"]["play_id"]
        if play_id in visited or play["c4"]["stage"] == TERM_STAGE:
            continue

        play_num += 1
        visited.append(play_id)

    active_plays = list(filter(lambda play: play["c4"]["stage"] != TERM_STAGE, plays))

    return f"^d^(Plays: {play_num} Instances: {len(active_plays)})^d^" if play_num > 0 else ""

if __name__ == "__main__":
    print(show_widget())
