#!/usr/bin/env bash

set -e

declare operation=$1
declare increment=$2

if (( increment < 0 )); then
  echo "invalid increment: $increment"
  exit 1
fi

if [[ "$operation" == "-m" ]]; then
	operation="-t"
fi

pamixer "$operation" "$increment"

# Signal dwmblocks to update volume in status bar
kill -44 "$(pidof dwmblocks)" &> /dev/null
