#!/usr/bin/env bash

is_muted() {
  pamixer --get-mute
}

get_volume() {
  pamixer --get-volume
}

declare output
color_unmuted="#42A5F5"
color_muted="#EC7875"

if [[ $(is_muted) == "true" ]]; then
  echo "^c$color_muted^ﱝ Muted"
  exit
else
  output="$(get_volume)"
fi

declare icon

if (( output >= 0 && output < 33 )); then
  icon="奄"  
elif (( output >= 33 && output < 66 )); then
  icon="奔"
elif (( output >= 66 && output <= 100 )); then
  icon="墳"
fi

echo "^c$color_unmuted^$icon^d^$output%"
