#!/usr/bin/env bash

set -e

declare operation=$1
declare increment=$2

if (( increment < 0 )); then
  echo "invalid increment: $increment"
  exit 1
fi

case $operation in
  -i) amixer set Master "$increment%+" ;;
  -d) amixer set Master "$increment%-" ;;
  -m) amixer set Master toggle ;;
  *) echo "invalid flag: $operation"; exit 1 ;;
esac

# Signal dwmblocks to update volume in status bar
kill -44 "$(pidof dwmblocks)" &> /dev/null
