#!/bin/bash

source "$HOME/.config/.weather_config"

api_uri="api.openweathermap.org/data/2.5/weather?units=metric&id=$WEATHER_CITY_ID&appid=$WEATHER_API_KEY"

declare -A icon_map=(
  [01d]=''         # Clear sky - day
  [01n]=''         # Clear sky - night
  [02d]=''         # Few clouds (11-25%) - day
  [02n]=''         # Few clouds (11-25%) - night
  [03d]=''         # Scattered clouds (25-50%) - day
  [03n]=''         # Scattered clouds (25-50%) - night
  [04d]=''         # Broken / Overcast clouds (51-84% / 85-100%) - day
  [04n]=''         # Broken / Overcast clouds (51-84% / 85-100%) - night
  [09d]=''         # Shower rain - day
  [09n]=''         # Shower rain - night
  [10d]=''         # Moderate / heavy rain - day
  [10n]=''         # Moderate / heavy rain - night
  [11d]=''         # Thunderstorm - day
  [11n]=''         # Thunderstorm - night
  [13d]=''         # Snow - day
  [13n]=''         # Snow - night
  [50d]=''         # Fog - day
  [50n]=''         # Fog - night
)

res="$(timeout 2 curl -s "$api_uri")"
if [[ $? != 0 ]] || [[ "$(jq -r .cod <<< "$res")" == 401 ]]; then
	echo "${icon_map[01d]}^d^-"
	exit
fi

if [[ $1 == "-p" ]]; then
  jq <<< "$res"
  exit
fi

icon_idx="$(jq -r '.weather[0].icon' <<< "$res")"
declare icon

if [[ "${icon_map[$icon_idx]+0}" ]]; then
  icon="${icon_map[$icon_idx]}"
else
  icon="$(jq -r '.weather[0].main' <<< "$res")"
fi

temp="$(printf %.0f "$(jq -r '.main.temp' <<< "$res")")"

echo "$icon^d^$temp°C"
